version: "3.8"
services:
    wehealth-panel:
        # image: centos:centos7
        build: ./ubuntu-php80
        image: ubuntu-php80
        container_name:  wehealth-panel
        hostname:  wehealth-panel
        volumes:
            - /docker-projects/wehealth.id/panel:/var/www/html/
            - /docker-projects/wehealth.id/media:/var/www/html/storage/app/public/
        environment:
            - DEBIAN_FRONTEND=noninteractive
            - TZ=Asia/Jakarta
        command: bash
        tty: true
        networks:
            - web-app-net
        restart: always

    wehealth-app:
        # image: centos:centos7
        build: ./ubuntu-php80
        image: ubuntu-php80
        container_name:  wehealth-app
        hostname:  wehealth-app
        volumes:
            - /docker-projects/wehealth.id/app:/var/www/html/
            - /docker-projects/wehealth.id/media:/var/www/html/storage/app/public/
        environment:
            - DEBIAN_FRONTEND=noninteractive
            - TZ=Asia/Jakarta
        command: bash
        tty: true
        networks:
            - web-app-net
        restart: always

    redis-master:
        container_name: redis-master
        image: redis:latest
        restart: always
        command: redis-server --port 6379
        ports:
            - 6379:6379

    redis-slave:
        container_name: redis-slave
        image: redis:latest
        restart: always
        command: redis-server --slaveof redis-master 6379
        depends_on:
            - redis-master
            
    nginx-proxy-ssl:
        # image: nginx:latest
        build: ./nginx-proxy-ssl
        image: nginx-proxy-ssl
        container_name: nginx-proxy-ssl
        hostname: nginx-proxy-ssl
        ports:
            - 80:80
            - 443:443
        volumes:
            - /docker-projects/nginx-proxy-ssl/nginx/:/etc/nginx/conf.d/
        networks:
            - web-app-net
        restart: always

networks:
    web-app-net:
        name: web-app-net
        driver: bridge
